In [ ]:
# 1. Import necessary libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report



In [ ]:
import pandas as pd  # Make sure pandas is imported

# Load your dataset
file_path = r'C:\Users\Srinjoy RayChaudhuri\Hackathon work\lung cancer data set.csv.csv'
data = pd.read_csv('lung cancer data set.csv.csv')

# Display the first few rows of the dataset
data.head()


In [21]:


# Load data from a CSV file (replace 'your_file.csv' with the actual filename)
data = pd.read_csv('lung cancer data set.csv.csv')

# Drop unnecessary columns if they exist in the data
if 'index' in data.columns and 'Patient Id' in data.columns:
    data = data.drop(['index', 'Patient Id'], axis=1)
    data = data.drop(columns=['Level'])

In [24]:
data.head()

Age  Gender  Air Pollution  Alcohol use  Dust Allergy  \
0   33       1              2            4             5   
1   17       1              3            1             5   
2   35       1              4            5             6   
3   37       1              7            7             7   
4   46       1              6            8             7   

   OccuPational Hazards  Genetic Risk  chronic Lung Disease  Balanced Diet  \
0                     4             3                     2              2   
1                     3             4                     2              2   
2                     5             5                     4              6   
3                     7             6                     7              7   
4                     7             7                     6              7   

   Obesity  ...  Coughing of Blood  Fatigue  Weight Loss  Shortness of Breath  \
0        4  ...                  4        3            4                    2   
1        2  ...                  3        1            3                    7   
2        7  ...                  8        8            7                    9   
3        7  ...                  8        4            2                    3   
4        7  ...                  9        3            2                    4   

   Wheezing  Swallowing Difficulty  Clubbing of Finger Nails  Frequent Cold  \
0         2                      3                         1              2   
1         8                      6                         2              1   
2         2                      1                         4              6   
3         1                      4                         5              6   
4         1                      4                         2              4   

   Dry Cough  Snoring  
0          3        4  
1          7        2  
2          7        2  
3          7        5  
4          2        3  

[5 rows x 23 columns]

In [29]:
print(data.columns)

Index(['Age', 'Gender', 'Air Pollution', 'Alcohol use', 'Dust Allergy',
       'OccuPational Hazards', 'Genetic Risk', 'chronic Lung Disease',
       'Balanced Diet', 'Obesity', 'Smoking', 'Passive Smoker', 'Chest Pain',
       'Coughing of Blood', 'Fatigue', 'Weight Loss', 'Shortness of Breath',
       'Wheezing', 'Swallowing Difficulty', 'Clubbing of Finger Nails',
       'Frequent Cold', 'Dry Cough', 'Snoring'],
      dtype='object')


In [5]:
# Encode categorical variables
# "Gender" is already numeric; however, "Level" (target) needs encoding
from sklearn.preprocessing import LabelEncoder

# Encode categorical variables
le = LabelEncoder()
data['Level'] = le.fit_transform(data['Level'])  # Encode target variable
  # Encode target variable

In [9]:

# Define features (X) and target (y)
X = data.drop('Level', axis=1)
y = data['Level']

In [8]:

# Split the data into training and testing sets
from sklearn.model_selection import train_test_split

# Assuming X and y are already defined
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [10]:
# Standardize the feature data
from sklearn.preprocessing import StandardScaler

# Standardize the feature data
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


In [11]:
# Initialize and train the model
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)


RandomForestClassifier(random_state=42)

In [12]:
# Make predictions
y_pred = model.predict(X_test)

In [14]:
from sklearn.metrics import accuracy_score

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")


Accuracy: 100.00%


In [ ]:
from sklearn.metrics import confusion_matrix, classification_report

# Print the confusion matrix and classification report
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred, target_names=le.classes_))


In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Initialize the Logistic Regression model
logistic_model = LogisticRegression(max_iter=1000, random_state=42)

# Train the model
logistic_model.fit(X_train, y_train)

# Make predictions
y_pred_logistic = logistic_model.predict(X_test)

# Evaluate Logistic Regression model
accuracy_logistic = accuracy_score(y_test, y_pred_logistic)
print(f"Logistic Regression Accuracy: {accuracy_logistic * 100:.2f}%")

# Print confusion matrix and classification report for Logistic Regression
print("Finding Logistic Regression Confusion Matrix:\n", confusion_matrix(y_test, y_pred_logistic))
print("Finding Logistic Regression Classification Report:\n", classification_report(y_test, y_pred_logistic, target_names=le.classes_))


In [27]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Define the parameter grid with compatible solver-penalty combinations
param_grid = {
    'C': [0.01, 0.1, 1, 10, 100],        # Regularization parameter
    'solver': ['liblinear', 'lbfgs'],     # Solvers for optimization
    'penalty': ['l2']                     # Only 'l2' penalty to avoid conflicts
}

# Since 'liblinear' can support both 'l1' and 'l2' penalties, we specify two grids separately
param_grid_liblinear = {
    'C': [0.01, 0.1, 1, 10, 100],
    'solver': ['liblinear'],
    'penalty': ['l1', 'l2']
}

# Combine the parameter grids
combined_param_grid = [param_grid, param_grid_liblinear]

# Initialize the Logistic Regression model
logistic_model = LogisticRegression(max_iter=1000, random_state=42)

# Initialize GridSearchCV with 5-fold cross-validation
grid_search = GridSearchCV(logistic_model, combined_param_grid, cv=5, scoring='accuracy', n_jobs=-1)

# Fit the model on training data
grid_search.fit(X_train, y_train)

# Print the best parameters found by GridSearchCV
print("Best parameters found by GridSearchCV:", grid_search.best_params_)

# Train the best model
best_logistic_model = grid_search.best_estimator_

# Make predictions using the best model
y_pred_logistic = best_logistic_model.predict(X_test)

# Evaluate Logistic Regression model with tuned parameters
accuracy_logistic = accuracy_score(y_test, y_pred_logistic)
print(f"Tuned Logistic Regression Accuracy: {accuracy_logistic * 100:.2f}%")

# Print confusion matrix and classification report for Logistic Regression
print("Tuned Logistic Regression Confusion Matrix:\n", confusion_matrix(y_test, y_pred_logistic))
print("Tuned Logistic Regression Classification Report:\n", classification_report(y_test, y_pred_logistic, target_names=le.classes_))



Best parameters found by GridSearchCV: {'C': 1, 'penalty': 'l2', 'solver': 'lbfgs'}
Tuned Logistic Regression Accuracy: 100.00%
Tuned Logistic Regression Confusion Matrix:
 [[82  0  0]
 [ 0 55  0]
 [ 0  0 63]]
Tuned Logistic Regression Classification Report:
               precision    recall  f1-score   support

        High       1.00      1.00      1.00        82
         Low       1.00      1.00      1.00        55
      Medium       1.00      1.00      1.00        63

    accuracy                           1.00       200
   macro avg       1.00      1.00      1.00       200
weighted avg       1.00      1.00      1.00       200



In [33]:
# Example of real-time or new data input (replace with actual new data)
#33,1,2,4,5,4,3,2,2,4,3,2,2,4,3,4,2,2,3,1,2,3,4
new_data = pd.DataFrame({
    'Age': [33],
    'Gender': [1],
    'Air Pollution': [2],
    'Alcohol use': [4],
    'Dust Allergy': [5],
    'OccuPational Hazards': [4],
    'Genetic Risk': [3],
    'chronic Lung Disease': [2],
    'Balanced Diet': [2],
    'Obesity': [4],
    'Smoking': [3],
    'Passive Smoker': [2],
    'Chest Pain': [2],
    'Coughing of Blood': [4],
    'Fatigue': [3],
    'Weight Loss': [4],
    'Shortness of Breath': [2],
    'Wheezing': [2],
    'Swallowing Difficulty': [3],
    'Clubbing of Finger Nails': [1],
    'Frequent Cold': [2],
    'Dry Cough': [3],
    'Snoring': [4]
})

# Preprocess the new data (use the same scaler and columns as in the training set)
new_data_scaled = scaler.transform(new_data)  # Scaling new data

# Make predictions with the trained model
predicted_class = best_logistic_model.predict(new_data_scaled)

# Decode the prediction to the original label
predicted_label = le.inverse_transform(predicted_class)

print(f"Predicted Level: {predicted_label[0]}")



Predicted Level: Low


In [32]:
from io import StringIO

# Define CSV data as a string
csv_data = """Age,Gender,Air Pollution,Alcohol use,Dust Allergy,OccuPational Hazards,Genetic Risk,chronic Lung Disease,Balanced Diet,Obesity,Smoking,Passive Smoker,Chest Pain,Coughing of Blood,Fatigue,Weight Loss,Shortness of Breath,Wheezing,Swallowing Difficulty,Clubbing of Finger Nails,Frequent Cold,Dry Cough,Snoring
28,1,3,2,4,5,3,2,2,4,2,1,3,1,3,2,2,3,1,2,3,3,4
45,0,2,4,5,3,4,3,1,3,4,2,4,2,4,3,4,1,2,4,2,3,3
50,1,5,6,7,5,6,5,1,7,6,3,5,3,5,4,5,4,5,5,6,5,7
"""

# Load the CSV data into a DataFrame
new_data = pd.read_csv(StringIO(csv_data))

# Preprocess the new data
new_data_scaled = scaler.transform(new_data)  # Assumes scaler is fitted

# Predict with the trained model
predictions = logistic_model.predict(new_data_scaled)

# Output predictions
print("Predictions:", predictions)


NotFittedError: This LogisticRegression instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.